# Generated by Django 2.0.3 on 2018-05-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
