# Generated by Django 2.0.3 on 2018-05-06 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20180505_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('squarefeet', models.IntegerField(null=True)),
                ('name', models.TextField()),
                ('hasbathroom', models.BooleanField(default=False)),
                ('hasawkwardlayout', models.BooleanField(default=False)),
                ('hascloset', models.BooleanField(default=False)),
                ('lease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Lease')),
                ('users', models.ManyToManyField(related_name='roomtenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
