# Generated by Django 2.0.3 on 2018-05-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='includecommonarea',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='rentscalefactor',
            field=models.IntegerField(null=True),
        ),
    ]
