# Generated by Django 2.0.3 on 2018-05-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180506_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_users_if_no_users',
            field=models.IntegerField(null=True),
        ),
    ]
