# Generated by Django 2.0.3 on 2018-05-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180508_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='num_users_if_no_users',
            new_name='num_users',
        ),
    ]
