# Generated by Django 2.0.3 on 2018-05-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180508_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
